-- =======================================================
-- Jayboi Giveaway - Supabase Database Schema
-- Run this in your Supabase SQL Editor to initialize
-- =======================================================

-- 1. Create the raffle_entries table
CREATE TABLE IF NOT EXISTS public.raffle_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE, -- Prevents duplicate entries from the same email
    phone TEXT,
    is_business_owner BOOLEAN DEFAULT FALSE,
    business_type TEXT,
    service_interest TEXT,
    newsletter_interest TEXT,
    raffle_number TEXT NOT NULL UNIQUE
);

-- 2. Set up Row Level Security (RLS)
ALTER TABLE public.raffle_entries ENABLE ROW LEVEL SECURITY;

-- 3. Create Policy: Allow public inserts (anyone can submit the form)
CREATE POLICY "Allow public insert" ON public.raffle_entries
    FOR INSERT
    TO public
    WITH CHECK (true);

-- 4. Create Policy: Allow public select (required for the admin dashboard to read if using anon key)
-- Note: In a true production app, you would lock this down to an authenticated admin role.
-- For this lightweight MVP, we allow read access via the anon key.
CREATE POLICY "Allow public select" ON public.raffle_entries
    FOR SELECT
    TO public
    USING (true);

-- =======================================================
-- Testing/Mock Data (Optional)
-- Remove the comment dashes below to insert a test row
-- =======================================================
-- INSERT INTO public.raffle_entries (full_name, email, phone, is_business_owner, service_interest, raffle_number)
-- VALUES ('Jayboi Test', 'test@jayboi.com', '555-555-5555', true, 'Web Design', 'JB-26-9999');
